/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/chazu/procyon/cmd/libtrashtalk */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 5 "main.go"

#include <stdlib.h>
#include <stdint.h>

// Forward declarations for types
typedef struct TTInstance TTInstance;
typedef struct TTBlock TTBlock;
typedef struct TTArray TTArray;

// TTValueType defines the type of a Trashtalk value
typedef enum {
    TT_TYPE_NIL = 0,
    TT_TYPE_INT = 1,
    TT_TYPE_FLOAT = 2,
    TT_TYPE_STRING = 3,
    TT_TYPE_BOOL = 4,
    TT_TYPE_INSTANCE = 5,
    TT_TYPE_BLOCK = 6,
    TT_TYPE_ARRAY = 7,
    TT_TYPE_ERROR = 8,
} TTValueType;

// TTValue is the universal value type
typedef struct {
    TTValueType type;
    union {
        int64_t intVal;
        double floatVal;
        const char* stringVal;
        TTInstance* instanceVal;
        TTBlock* blockVal;
        TTArray* arrayVal;
    };
} TTValue;

// Method function pointer type
typedef TTValue (*TTMethodFunc)(TTInstance* self, TTValue* args, int numArgs);

// Method flags
typedef enum {
    TT_METHOD_NATIVE = 1,
    TT_METHOD_BASH_FALLBACK = 2,
    TT_METHOD_CLASS_METHOD = 4,
} TTMethodFlags;

// Method entry
typedef struct {
    const char* selector;
    TTMethodFunc impl;
    int numArgs;
    uint32_t flags;
} TTMethodEntry;

// Method table
typedef struct {
    TTMethodEntry* instanceMethods;
    int numInstanceMethods;
    TTMethodEntry* classMethods;
    int numClassMethods;
} TTMethodTable;


#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int TT_Init(char* dbPath, char* pluginDir);
extern void TT_Close();
extern void TT_RegisterClass(char* className, char* superclass, char** instanceVars, int numVars, TTMethodTable* methods);
extern char* TT_New(char* className);
extern TTInstance* TT_Lookup(char* instanceID);
extern TTValue TT_GetIVar(TTInstance* inst, char* name);
extern void TT_SetIVar(TTInstance* inst, char* name, TTValue val);
extern TTValue TT_GetIVarByIndex(TTInstance* inst, int index);
extern void TT_SetIVarByIndex(TTInstance* inst, int index, TTValue val);
extern TTValue TT_Send(char* receiver, char* selector, TTValue* args, int numArgs);
extern TTValue TT_SendDirect(TTInstance* inst, char* selector, TTValue* args, int numArgs);
extern char* TT_RegisterBlock(uint8_t* bytecodeData, size_t bytecodeLen, TTValue** captures, int numCaptures);
extern TTBlock* TT_LookupBlock(char* blockID);
extern TTValue TT_InvokeBlock(char* blockID, TTValue* args, int numArgs);
extern TTValue TT_InvokeBlockDirect(TTBlock* block, TTValue* args, int numArgs);
extern int TT_Persist(char* instanceID);
extern TTInstance* TT_Load(char* instanceID);
extern char* TT_BashFallback(char* receiver, char* selector, char** args, int numArgs);
extern TTValue TT_MakeNil();
extern TTValue TT_MakeInt(int64_t n);
extern TTValue TT_MakeFloat(double f);
extern TTValue TT_MakeString(char* s);
extern TTValue TT_MakeBool(int b);
extern char* TT_ValueAsString(TTValue val);
extern int64_t TT_ValueAsInt(TTValue val);
extern char* TT_ValueToJSON(TTValue val);
extern char* TT_Serialize(TTInstance* inst);
extern TTInstance* TT_Deserialize(char* jsonStr);
extern char* TT_GetInstanceID(TTInstance* inst);
extern char* TT_GetInstanceClass(TTInstance* inst);
extern TTValue TT_MakeInstance(TTInstance* inst);
extern char* TT_GetLastError();

#ifdef __cplusplus
}
#endif
